### ISSUE TITLE
ESP32-S3-DevKitC-1-N32R8 with ESP32S3 - NEOPIXEL issue

### ISSUE THREAD

**Issue by roshanrenguin** [adafruit/circuitpython#9376] opened 2024-06-26 19:41 UTC
### CircuitPython version

```python
CircuitPython 9.0.5 and CircuitPython 9.1.0-beta.3
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2022 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT
import time
import board
from rainbowio import colorwheel
import neopixel

NUMPIXELS = 16  # Update this to match the number of LEDs.
SPEED = 0.05  # Increase to slow down the rainbow. Decrease to speed it up.
BRIGHTNESS = 0.2  # A number between 0.0 and 1.0, where 0.0 is off, and 1.0 is max.
PIN = board.NEOPIXEL  # This is the default pin on the 5x5 NeoPixel Grid BFF.

pixels = neopixel.NeoPixel(PIN, NUMPIXELS, brightness=BRIGHTNESS, auto_write=False)


def rainbow_cycle(wait):
    for color in range(255):
        for pixel in range(len(pixels)):  # pylint: disable=consider-using-enumerate
            pixel_index = (pixel * 256 // len(pixels)) + color * 5
            pixels[pixel] = colorwheel(pixel_index & 255)
        pixels.show()
        time.sleep(wait)


while True:
    rainbow_cycle(SPEED)
```

### Behavior

PIN = board.NEOPIXEL  # Doesnt work

### Description

]0;🐍192.168.1.38 | REPL | 9.1.0-beta.3\

Adafruit CircuitPython 9.1.0-beta.3 on 2024-05-22; ESP32-S3-DevKitC-1-N32R8 with ESP32S3

>>> import board
>>> dir(board)
['__class__', '__name__', 'IO0', 'IO1', 'IO10', 'IO11', 'IO12', 'IO13', 'IO14', 'IO15', 'IO16', 'IO17', 'IO18', 'IO19', 'IO2', 'IO20', 'IO21', 'IO3', 'IO35', 'IO36', 'IO37', 'IO38', 'IO39', 'IO4', 'IO40', 'IO41', 'IO42', 'IO43', 'IO44', 'IO45', 'IO46', 'IO47', 'IO48', 'IO5', 'IO6', 'IO7', 'IO8', 'IO9', 'NEOPIXEL', 'RX', 'TX', 'UART', '__dict__', 'board_id']
>>> 

### Additional information

PIN = board.NEOPIXEL  # Doesnt work
It works if  replaced with 'PIN = board.IO38'

**Comment by dhalbert** [comment] 2024-06-26 19:47
This is a dupe of https://github.com/adafruit/circuitpython/issues/9275. Espressif moved the NeoPixel pin from v1.0 to v1.1 of this board. A new board definition needs to be made.

**Closed by dhalbert** 2024-06-26 19:47 UTC
Labels: bug
