### ISSUE TITLE
Read the docs link for CircuitPython don't work

### ISSUE THREAD

**Issue by dannystaple** [adafruit/circuitpython#5763] opened 2021-12-22 16:57 UTC
### CircuitPython version

```python
NA
```

### Code/REPL

```python
NA
```

### Behavior

NA

### Description

I get a 404 if I click the Edit On Github links in the Documentation. This may be a readthedocs issue, or a configuration issue in the doc generation.

Reproducing this:

- Open a document in CircuitPython readthedocs - ie https://circuitpython.readthedocs.io/en/latest/shared-bindings/rp2pio/#rp2pio.StateMachine.readinto. 
- Click the "Edit on GitHub" button.

Result:

- Takes you to the link "https://github.com/adafruit/circuitpython/blob/main/shared-bindings/rp2pio/index.rst" - which is a 404 on github.

Expected:
It should probably link to https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/bindings/rp2pio - since the module doc is in the C code here.

**Comment by jepler** [comment] 2022-01-08 03:55
Because of the way we generate the documentation, it may be best if we can just turn off those links. it's probably possible in sphinx configuration, if someone wants to go looking for it.

**Comment by tekktrik** [comment] 2022-01-14 18:16
Here's how to do it: https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html

**Comment by tekktrik** [comment] 2022-01-14 18:16
I can give this a shot

**Comment by tekktrik** [comment] 2022-01-15 19:32
Not entirely sure this fixed the issue, I still see the links in the top right corner...

**Comment by jepler** [comment] 2022-01-15 20:32
![image](https://user-images.githubusercontent.com/1517291/149636834-2adf3f8c-b396-46ec-8aa5-17f2eb217376.png)
 yeah I am seeing the same thing, unfortunately.

**Comment by jepler** [comment] 2022-01-15 20:32
I confirmed that github built main after #5863 was merged in

**Comment by tekktrik** [comment] 2022-01-15 22:16
I'll see if I can build RTD locally and follow up to this with a solution.  I've had issues building locally before but I'll see if I can over come that and solve this!

**Closed** 2022-04-25 13:07 UTC
Labels: bug, help wanted, documentation
