### ISSUE TITLE
XIAO nRF52840 reset into BOOTLOADER or UF2 modes behaves as a normal reset starting with version 9.1.0

### ISSUE THREAD

**Issue by jordan1110** [adafruit/circuitpython#9584] opened 2024-08-31 03:52 UTC
### CircuitPython version

```python
Adafruit CircuitPython 9.1.3 on 2024-08-29; Seeed XIAO nRF52840 Sense with nRF52840
Adafruit CircuitPython 9.1.2 on 2024-08-22; Seeed XIAO nRF52840 Sense with nRF52840
Adafruit CircuitPython 9.1.0 on 2024-07-10; Seeed XIAO nRF52840 Sense with nRF52840
Adafruit CircuitPython 9.0.5 on 2024-05-22; Seeed XIAO nRF52840 Sense with nRF52840
```

### Code/REPL

```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.BOOTLOADER)
microcontroller.reset()
```

### Behavior

Using versions 9.1.0 and newer, attempts to reset to BOOTLOADER or UF2 modes, the XIAO resets but then runs in normal mode.

### Description

This worked in version 9.0.5 but stopped working in version 9.1.0 and newer. Booting to SAFE_MODE continues to work in all versions 9.05 thru 9.1.3.

**Comment by dhalbert** [comment] 2024-08-31 19:44
Sorry - I had retested #9423, and thought it was working. I've reopened that issue, which has a little more detail, and will close this one as a dupe of #9423. I'll ping you in #9423 so you can track it.

**Closed** 2024-09-01 02:09 UTC
Labels: bug
