### ISSUE TITLE
I2CPeripheral support on RP2040 boards

### ISSUE THREAD

**Issue by domdfcoding** [adafruit/circuitpython#5410] opened 2021-09-30 10:46 UTC
Hi,

Would it be possible to add the `i2cperipheral` module to RP2040-based boards like the Pico? It looks like the Pico SDK has an [`i2c_set_slave_mode`](https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__i2c.html#ga42571b2db5d1ed0dc083385c230dc9e8) function so set one of the i2c ports into slave mode. Presumably that could be used as the basis of an implementation?

**Comment by microDev1** [comment] 2021-09-30 12:14
It is certainly possible to add `i2cperipheral` on `RP2040` now that the `pico-sdk` has support for it.

**Comment by dhalbert** [comment] 2022-01-09 00:06
Duplicate of #4536. I'll copy your comment over.

**Closed by dhalbert** 2022-01-09 00:06 UTC
Labels: enhancement, circuitpython api, rp2
