### ISSUE TITLE
Disable REPL to use USB UART for custom console?

### ISSUE THREAD

**Issue by AdinAck** [adafruit/circuitpython#2860] opened 2020-05-06 06:29 UTC
I am using an M4 ItsyBitsy and would like to create a custom console for when I plug my computer into the USB port on the ItsyBitsy. I don't know how to access the Tx and Rx pins on the USB port and I don't know if I would be able to use them even if I did know what pins they were since the REPL uses them. And yes I know that there is input() and print() but I need background processes to occur even while the user is using the console (since input() holds the whole script).

Is there any way to accomplish this?

Thanks!

**Comment by deshipu** [comment] 2020-05-06 13:10
There are on TX and RX pins on the USB port — that serial port is virtual, simulated in software.

If you want non-blocking input, you will probably be interested in issue #231.

**Comment by tannewt** [comment] 2020-05-06 17:25
Closing this because it is a duplicate of #231.

**Closed by tannewt** 2020-05-06 17:25 UTC
