### ISSUE TITLE
adafruit_hid.keyboard doesn't work when using storage.disable_usb_drive() [Windows 7/8.1 problem]

### ISSUE THREAD

**Issue by st42** [adafruit/circuitpython#5382] opened 2021-09-22 18:16 UTC
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
#code.py
import usb_hid
from adafruit_hid.keyboard import Keyboard

kbd = Keyboard(usb_hid.devices)

#boot.py
import storage

storage.disable_usb_drive()
```

### Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "adafruit_hid/keyboard.py", line 65, in __init__
  File "adafruit_hid/keyboard.py", line 113, in release_all
OSError: USB busy
```

### Description

I was trying to get the Pico to only be recognized as a usb keyboard and discovered that adafruit_hid.keyboard doesn't work with storage.disable_usb_drive(). I stripped away all of the unnecessary code in code.py and boot.py to show the error. I was using the Thonny IDE to view the output.

This error only occurs in Windows. It doesn't happen in Raspberry Pi OS.

I was using adafruit_hid.keyboard from adafruit-circuitpython-bundle-7.x-mpy-20210922.zip

**Comment by dhalbert** [comment] 2021-09-22 18:29
I tried this on a Dell Optiplex 3020 running Windows 10 and could not reproduce the problem. It may be a slow USB startup. What is your host computer and what version of Windows is it running?

Try inserting a `time.sleep()` of a few seconds at the beginning of code.py, before the `Keyboard()` instantiation, and see if that makes a difference for you.

**Comment by st42** [comment] 2021-09-22 19:16
My computer is a HP Pavilion p6320y running Windows 7 Home Premium. I tried a 10 second sleep just for good measure but the error still occurs.

**Comment by dhalbert** [comment] 2021-09-22 19:25
Do you have a Windows 10 computer to try?

**Comment by st42** [comment] 2021-09-22 19:27
I don't have a Win 10 computer unfortunately

**Comment by dhalbert** [comment] 2021-09-27 15:27
Try disabling serial as well. Add these lines to your `boot.py`:

```py
import usb_cdc

usb_cdc.disable()
```
Our Windows Drivers installer does not yet support the Pi Pico, and that _may_ have something to do with this.

Also try Uwe Seiber's USB Device Cleanup tool, which may remove some bad state: https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting#device-errors-or-problems-on-windows-3094694-15

**Comment by dhalbert** [comment] 2021-10-11 22:59
I am changing this to Long Term because the problem is Windows 7/8.1 specific. There are restrictions caused by the Windows 7/8.1 drivers about the Interface numbers of the drivers. We also need to update the drivers package to include the Pi Pico. But this is not a problem we can fix in CircuitPython.

When I update the drivers we can try this again.

**Comment by dhalbert** [comment] 2023-10-28 17:39
Closing because we have no plans to update the Windows 7/8.1 drivers.

**Closed by dhalbert** 2023-10-28 17:39 UTC
Labels: bug, usb
