### ISSUE TITLE
Crash to HardFault handler while testing MCP4728 lib on M4 w/ 5.0 Beta 1

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython#2408] opened 2019-12-19 02:27 UTC
I was testing my new MCP4728 library when I got a crash into the hardfault handler. Power cycling the device made the issue go away

Hardware is a Metro m4 (purple) with 5.0 Beta 1. The driver in question is an I2C based driver using bus_device but not register. The only connections to the metro were power+I2C.

The crash happed right after my discovery the CP `bytearray` does not in fact have `insert`. I was in the process of moving to use `extend` instead when the crash happened.

Possibly relevant context is that I've been and was using a small utility script that I wrote based on `fswatch`: https://github.com/emcrisostomo/fswatch

I have it setup to copy the lib over to my `CIRCUITPY/lib` whenever it detects a file change. VScode writes to the file automatically every few seconds if there are changes so it's certainly possible, even likely that it copied over the file in some syntax-incomplete form before copying over an updated version seconds later.

**Comment by dhalbert** [comment] 2023-10-28 15:07
Closing this because we don't have code for reproduction.

**Closed by dhalbert** 2023-10-28 15:07 UTC
Labels: bug, atmel-samd, crash, circuitpython api, needs retest
