### ISSUE TITLE
time.sleep() in code.py prevents USB from working

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2912] opened 2020-05-16 15:51 UTC
This may be a dupe of the other USB issues we are seeing with `lower_power`.

If this is `code.py`, USB doesn't connect: no CIRCUITPY and no REPL
```python
import time
while True:
    print('hi')   # not necessary, just easier to see it's running
    time.sleep(1)
```

**Comment by xobs** [comment] 2020-05-18 06:11
This is a duplicate of https://github.com/adafruit/circuitpython/issues/2855 and is fixed by https://github.com/adafruit/circuitpython/pull/2868

**Comment by dhalbert** [comment] 2020-05-18 13:13
I neglected to say I was seeing this issue on SAMD21 boards (CPX and Metro M0). I could not reproduce it on SAMD51, though it's probably an accident that it works :). The #2868 fix is specific to `nrf`, so we'll need fixes for other ports too.

**Closed** 2020-05-26 21:54 UTC
Labels: usb
