### ISSUE TITLE
SPI + Bluetooth crash nRF52840

### ISSUE THREAD

**Issue by urish** [adafruit/circuitpython#1222] opened 2018-09-30 23:21 UTC
Calling the `write()` method of an SPI object while Bluetooth is active crashes the firmware. 

Here is a minimal code that reproduces the issue:

```python
import board
import busio
from ubluepy import Peripheral

p = Peripheral()
p.advertise()

spi = busio.SPI(board.P0_22, MOSI=board.P1_00)
while not spi.try_lock():
    pass
spi.write(bytes([0xff]))
```

If you comment out the last line (the call to `spi.write()`), then it doesn't crash anymore. Tested on the nRF52840 USB Dongle.

**Comment by jerryneedell** [comment] 2018-10-03 13:34
FYI - I can reproduce this on my nrf52840_dongle but it does not fail on a feather_nrf52832

**Comment by jerryneedell** [comment] 2018-10-06 18:13
A bit more information -- I was able to successfully mount my SDCard -- SPI device and then initialte a BLE advertisement and it runs OK - however if I then access the SDCard the system resets as above.

**Comment by urish** [comment] 2018-10-06 21:15
I am observing the same as @jerryneedell

**Comment by urish** [comment] 2018-10-06 23:05
Positive outcome from this issue - a blog post describing how to optimize the performance of CircuitPython code:

https://medium.com/@urish/embedded-python-cranking-performance-knob-up-to-eleven-df31a5940a63

**Comment by dhalbert** [comment] 2018-10-10 01:38
I spent some time on this, but didn't discover the root cause. I tried other pins, including ones that are definitely marked as safe for high-speed I/O. It seems like there's reset when the SPI write is attempted. Nothing appears on the SPI pions.

**Comment by jerryneedell** [comment] 2018-10-10 01:41
Since it does not occur on the nrf52832, It could be related to the s140 SD or something in the nrf52840 code. Both are differences.

**Comment by jerryneedell** [comment] 2018-10-11 00:00
just for fun - I tried accessing an I2C device while BLE was active on a PCA10059 Dongle and it eorked fine.

**Comment by dhalbert** [comment] 2018-10-11 01:14
I also tried I2C, and also UART, and neither caused a problem. It seems to be SPI in particular. I looked at the code and I don't see anything obvious. I changed the `HardFault_Handler()` to hang (as it does in `atmel-samd`) instead of just returning and maybe I can catch the problem. Will report back.

The SoftDevice documentation describes how reserves a few peripherals for its own use (like TIMER0) or provides only a restricted API to a shared peripheral, but I don't see any conflicts.

**Comment by dhalbert** [comment] 2018-10-12 01:07
This BLE + SPIM crash sounds quite similar to this issue: https://devzone.nordicsemi.com/f/nordic-q-a/33982/sdk-15-software-crash-during-spi-session/130572. I'm inquiring.

**Comment by jerryneedell** [comment] 2018-10-12 14:03
Not the most encouraging response to your inquiry :-(

**Comment by arturo182** [comment] 2018-10-12 14:09
Have you tried building a DEBUG build, it has asserts enabled, maybe that helps.

**Comment by jerryneedell** [comment] 2018-10-12 15:36
I disabled SPIM3 in nrfx_config.h and the problem seems to have been resolved.  I can now run a blue advertise and then mount my SPI SD Card

**Comment by tannewt** [comment] 2019-02-05 00:34
Can we close this?

**Comment by tannewt** [comment] 2019-02-05 04:51
Ok, I'm moving to 4.x. We don't need it for 4.0.0

**Comment by dhalbert** [comment] 2019-02-05 04:54
Fine to defer!

**Comment by dhalbert** [comment] 2019-10-17 03:13
@hathach has gotten SPIM3 to work with BLE in use on Arduino, so this should be retested, trying to duplicate those conditions.

**Comment by dhalbert** [comment] 2019-10-22 23:40
Just found this in the nRF SDK release notes for v15.3.0:

> The workaround for Anomaly 198 for nRF52840 SPIM3 peripheral that has been implemented in nrfx_spim cannot be used with a SoftDevice.
> Flag NRFX_SPIM3_NRF52840_ANOMALY_198_WORKAROUND_ENABLED must be set to zero.
> The workaround based on a dedicated RAM block for SPIM3 must be used instead.

**Comment by hathach** [comment] 2019-10-23 04:30
a RAM block according to interconnect diagram is probably a 8KB of RAMx.
![image](https://user-images.githubusercontent.com/249515/67357749-7ba0bd80-f588-11e9-9252-c401812bfc7c.png)

**Closed** 2020-02-12 03:55 UTC
Labels: bug, crash, nrf52
