### ISSUE TITLE
dir(cp) doesn't work

### ISSUE THREAD

**Issue by ajs256** [adafruit/circuitpython#3748] opened 2020-11-20 01:49 UTC
```
>>> from adafruit_circuitplayground import cp
>>> dir(cp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_circuitplayground/express.py", line 82, in _unsupported
NotImplementedError: This feature is not supported on Circuit Playground Express.
>>> import math # to check that dir() works on something else
>>> dir(math)
['__class__', '__name__', 'acos', 'asin', 'atan', 'atan2', 'ceil', 'copysign', 'cos', 'degrees', 'e', 'exp', 'fabs', 'floor', 'fmod', 'frexp', 'isfinite', 'isinf', 'isnan', 'ldexp', 'log', 'modf', 'pi', 'pow', 'radians', 'sin', 'sqrt', 'tan', 'trunc']
```
I am not sure why this is happening. `cp` imports correctly, but `dir(cp)` doesn't work.

**Comment by DavePutz** [comment] 2020-11-28 20:54
It looks like this is being caused by PR #86 to the adafruit/Adafruit_CircuitPython_CircuitPlayground library . By adding a property of "_unsupported" to the Express class, which raises a NotImplementedError when accessed, it causes any process (like 'dir(cp)) which accesses that property to stacktrace. I guess the question is whether it is more valuable to have a good message when someone tries to access a non-existent feature or to have commands like dir() work.

**Comment by dhalbert** [comment] 2021-02-11 16:40
Closing in favor of dupe #4171, which has a bit more discussion.

**Closed by dhalbert** 2021-02-11 16:40 UTC
Labels: bug, cpython api, micropython core
