### ISSUE TITLE
PYPORTAL file loss

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1579] opened 2019-02-21 01:45 UTC
Since i upgraded to the most recent master,4.0.0-beta.2-97-g0dc260058 on 2019-02-20
, occasionally while editing with mu the pytportal freezes up and the led goes red and the mounted drive will freeze up and crash too if you try to interact with it. then when unplugged and re-plugged some file on the drive will be corrupted, or an entire folder. i have a jtag edu with me (the large one) if you think that could help. this is the only board this happens on that i have. i wish i had more data to report

**Comment by ladyada** [comment] 2019-02-21 02:24
this this a duplicate of https://github.com/adafruit/circuitpython/issues/1577#issuecomment-465834205 ?

**Comment by tannewt** [comment] 2019-02-21 18:52
Let's focus on #1577. These are similar enough that we only need one.

**Closed by tannewt** 2019-02-21 18:52 UTC
