### ISSUE TITLE
REPL:  TypeError exceptions missing operator name for some operators

### ISSUE THREAD

**Issue by ddiminnie** [adafruit/circuitpython#1214] opened 2018-09-25 18:06 UTC
This is another minor issue, though it can make debugging code somewhat problematic.
(Observed in 'Adafruit CircuitPython 3.0.0 on 2018-07-09; Adafruit Gemma M0 with samd21e18'.)

When evaluating functions or executing instructions in the REPL, TypeError exceptions thrown by certain operators do not include the operator name.

For example:
`>>> a = 2`
`>>> b = 'a'`
`>>> a/b`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`TypeError: unsupported types for : 'int', 'str'`

This isn't too problematic when there is only one operator in use, but is more of a problem when trying to debug statements like
`var1 op var2 op (var3 op var4) op var5`
(Which operation failed in this statement??)

A partial list of operators for which the above behavior occurs is:
`-` (unary minus)
`>>`
`<<`
`*`
`**`
`/`
`//`
`%`
`|`
`^`
`~`

**Comment by theacodes** [comment] 2019-10-08 21:33
I tried reproducing this with the Unix port, but it seems to be working as expected. Is this still an issue?

**Comment by tannewt** [comment] 2019-10-10 03:47
@theacodes Not if you couldn't repro. Will close it.

**Closed by tannewt** 2019-10-10 03:47 UTC
Labels: cpython api, enhancement, help wanted

**Comment by theacodes** [comment] 2019-10-10 17:16
I'll try it out on a CPX later tonight and report back.

**Comment by theacodes** [comment] 2019-10-11 02:30
From CircuitPython 4.0.1 on a Feather M4 Express:

```
>>> a = 2
>>> b = 'a'
>>> a/b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert 'int' object to str implicitly

>>> -b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported type for __neg__: 'str'
```

```
>>> a = object()
>>> b = object()
>>> a / b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __truediv__: 'object', 'object'

>>> a * b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __mul__: 'object', 'object'

>>> a >> b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __rshift__: 'object', 'object'

>>> a << b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __lshift__: 'object', 'object'

>>> a ** b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __pow__: 'object', 'object'

>>> a % b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __mod__: 'object', 'object'

>>> a | b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __or__: 'object', 'object'

>>> a & b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __and__: 'object', 'object'

>>> a ^ b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported types for __xor__: 'object', 'object'

>>> ~a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported type for __invert__: 'object'
```

Seems like it's no longer an issue. 👍

**Comment by ddiminnie** [comment] 2019-10-11 15:01
@theacodes :

Great!

Thanks for checking.
