### ISSUE TITLE
library module adafruit_ble_broadcastnet error in line 171

### ISSUE THREAD

**Issue by ray-5050** [adafruit/circuitpython#4496] opened 2021-03-26 18:52 UTC
**Firmware**
Tried both the 6.1.1 stable and the below with same results on the feather nrf52840
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit Feather nRF52840 Express with nRF52840

```python
tried 2 versions on the feather nrf52840
adafruit-circuitpython-bundle-6.x-mpy-20210303
adafruit-circuitpython-bundle-6.x-mpy-20210326

The code.py is the example ble_broadcastnet_battery_level.py
I'm getting the below error in the library adafruit_ble_broadcastnet
line 171   self.data_dict[255].data.move_to_end(3, last=False)
When I type that command in, I do get a attribute for move_to_end

code.py output:
This is BroadcastNet sensor: d707ed9caad1
<AdafruitSensorMeasurement temperature=24.0 battery_voltage=4112 >
Traceback (most recent call last):
  File "code.py", line 25, in <module>
  File "adafruit_ble_broadcastnet.py", line 37, in broadcast
  File "adafruit_ble/__init__.py", line 166, in start_advertising
  File "adafruit_ble_broadcastnet.py", line 171, in __bytes__
AttributeError: 'OrderedDict' object has no attribute 'move_to_end'

Thanks for your help

**Comment by ladyada** [comment] 2021-03-26 19:57
this is duplicate of https://github.com/adafruit/Adafruit_CircuitPython_BLE_BroadcastNet/issues/18

**Closed by ladyada** 2021-03-26 19:57 UTC
Labels: bug
