### ISSUE TITLE
busdevice setup/init not working on 6.1.0 w/ CLUE nRF52840

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython#3891] opened 2020-12-29 03:50 UTC
Using the following test code and a SGP40 attached to the CLUEs Stemma QT port,
```
import board
import busio
import adafruit_bus_device.i2c_device as i2c_device

i2c = busio.I2C(board.SCL, board.SDA)
i2c_device = i2c_device.I2CDevice(i2c, 0x59)
print("i2c_device 'found'")
```
with **6.0.1** I get:
![image](https://user-images.githubusercontent.com/1183985/103257187-0e837780-4945-11eb-8284-c1d02a6404ff.png)

with **6.1.0 Beta 2** I get:
![image](https://user-images.githubusercontent.com/1183985/103257158-f01d7c00-4944-11eb-8d53-0cc8b4c52ccb.png)

The only change here is flashing the new version

Interestingly, an I2C scan works as expected with 6.1.0 Beta 2:
![image](https://user-images.githubusercontent.com/1183985/103257379-da5c8680-4945-11eb-9f84-08173f6a08ed.png)

**Comment by dhalbert** [comment] 2020-12-29 04:44
Maybe this is a dupe of #3795, fixed by #3847. But we are disabling native busdevice for now due to other issues: #3869.

You could test against the artifacts from #3847. For the CLUE, try https://adafruit-circuit-python.s3.amazonaws.com/bin/clue_nrf52840_express/en_US/adafruit-circuitpython-clue_nrf52840_express-en_US-20201218-fd21ff5.uf2. That is the #3847 merge commit, and is before #3869.

**Comment by siddacious** [comment] 2020-12-29 21:21
@dhalbert looks the same with the uf2 you linked to:
![image](https://user-images.githubusercontent.com/1183985/103314659-88187580-49d8-11eb-8b6f-bd8ece36b594.png)
![image](https://user-images.githubusercontent.com/1183985/103314740-b7c77d80-49d8-11eb-99e9-b7dd4fd7383d.png)

**Comment by dhalbert** [comment] 2020-12-30 03:33
Hmm, that's not what I expected. Could you also try the absolute latest from here: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/clue_nrf52840_express/en_US/

**Comment by siddacious** [comment] 2021-01-04 18:02
@dhalbert I tested the latest and it seems to work. 

I tested the previous (`d21ff5`) again as well and confirmed the failure.

Lmk what else you'd like me to try

**Comment by dhalbert** [comment] 2021-01-04 18:40
OK, great! So let's close this for now, and we'll make sure to retest when we get around to putting back native bus device.

**Closed by dhalbert** 2021-01-04 18:40 UTC
Labels: bug, busio, nrf52
