### ISSUE TITLE
Freaky/Slow asyncio behavior on RP2040 XIAO 8.0.0-beta 3

### ISSUE THREAD

**Issue by xgpt** [adafruit/circuitpython#7136] opened 2022-10-27 16:26 UTC
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.3 on 2022-10-20; Seeeduino XIAO RP2040 with rp2040
Board ID:seeeduino_xiao_rp2040
UID:415032383337320B
boot.py output:
```

### Code/REPL

```python
"""why does code.py need a docstring for pylint?"""

import adafruit_ssd1306
import asyncio
import board
import busio
import digitalio
import time


class Led:
    """simple LED blinky example class"""

    def __init__(self):
        """shush pylint"""

        self.led = digitalio.DigitalInOut(board.LED_BLUE)
        self.led.switch_to_output()
        self.led.value = 1

    def toggle_led(self):
        """shush pylint"""
        self.led.value = not self.led.value


class Screen:
    """simple class for example display control"""

    def __init__(self):
        """shush pylint"""

        i2c = busio.I2C(board.SCL, board.SDA)

        # self.reset_pin = digitalio.DigitalInOut(board.IO13) # any pin!
        self.oled = adafruit_ssd1306.SSD1306_I2C(
            128, 32, i2c
        )  # , reset=self.reset_pin)
        self.oled.rotate(0)
        self.line_1 = "line 1"
        self.line_2 = "line 2"
        self.line_3 = "line 3"
        self.line_4 = "line 4"

    def update_text(self, invert=0):
        """shush pylint"""
        white = 1
        black = 0
        if invert:
            white = 0
            black = 1
        self.oled.fill(black)
        self.oled.text(str(" " + self.line_1), 0, 0 * 1, white)
        self.oled.text(str(" " + self.line_2), 0, 8 * 1, white)
        self.oled.text(str(" " + self.line_3), 0, 8 * 2, white)
        self.oled.text(str(" " + self.line_4), 0, 8 * 3, white)
        self.oled.show()


class Button:
    """simple class for IO control"""

    def __init__(self):
        """shush pylint"""

        self.button = digitalio.DigitalInOut(board.D6)
        self.button.switch_to_input(pull=digitalio.Pull.UP)

    def is_pressed(self):
        """shush pylint"""
        if not self.button.value:
            return 1
        return 0


class Counter:
    """simple class for counting a thing"""

    def __init__(self):
        """shush pylint"""
        self.value = 0
        self.max = 20

    def increment(self):
        """shush pylint"""
        self.value += 1
        if self.value > self.max:
            self.value = 1


async def print_func():
    """shush pylint"""
    while 1:
        print(time.monotonic())
        print("print_func")
        await asyncio.sleep(0.1)


async def led_blink():
    """shush pylint"""
    while 1:
        line_1.toggle_led()
        await asyncio.sleep(0.2)


async def button_check():
    """shush pylint"""
    while 1:
        if butt.is_pressed():
            print("old:", counter_object.value)
            counter_object.increment()
            print("new:", counter_object.value)
        else:
            print("not pressed")
            await asyncio.sleep(0.1)


async def main():
    """shush pylint"""
    button_task = asyncio.create_task(button_check())
    led_task = asyncio.create_task(led_blink())
    print_task = asyncio.create_task(print_func())
    await asyncio.gather(button_task, led_task, print_task)
    print("wut")


line_1 = Led()
display = Screen()
butt = Button()
print(butt.button.value)
counter_object = Counter()

display.oled.fill(1)
display.oled.show()

print("begin")

print(time.monotonic())
asyncio.run(main())
print("end")
```

### Behavior

runs as expected, but hangs on line
```python
asyncio.run(main())
```
 prior to any LED blinking happening for a solid 2 minutes and 18 seconds (I recorded it with my phone and checked timestamps)

**Comment by xgpt** [comment] 2022-10-27 16:27
Please ignore all the weird pylint docstring stuff, was cracking jokes in the channel at how bad pylint was grading my example code...shouldn't affect performance.

**Comment by xgpt** [comment] 2022-10-27 16:33
Just because I thought it might...idk...change behavior in some way...I compiled mpy-cross to compiled code.py to code.mpy...

made no difference in execution time.

```
Adafruit CircuitPython 8.0.0-beta.3 on 2022-10-20; Seeeduino XIAO RP2040 with rp2040
>>> import code.mpy
True
begin
8.913
```

**Comment by dhalbert** [comment] 2022-10-27 16:39
Could you try this with 8.0.0-beta.2 and beta.1? There have been significant changes to asyncio since then. If those don't make a difference try rolling back the asyncio library to https://github.com/adafruit/Adafruit_CircuitPython_asyncio/releases/tag/0.5.16, and then trying those betas again? Thanks.

**Comment by xgpt** [comment] 2022-10-27 16:43
yessir

**Comment by xgpt** [comment] 2022-10-27 16:48
@dhalbert that fixed it straightaway. revert to beta 2.

**Comment by xgpt** [comment] 2022-10-27 16:49
```python
"""why does code.py need a docstring for pylint?"""

#import adafruit_ssd1306
import asyncio
import board
import busio
import digitalio
import time


class Led:
    """simple LED blinky example class"""

    def __init__(self):
        """shush pylint"""

        self.led = digitalio.DigitalInOut(board.LED_BLUE)
        self.led.switch_to_output()
        self.led.value = 1

    def toggle_led(self):
        """shush pylint"""
        self.led.value = not self.led.value


#class Screen:
#    """simple class for example display control"""
#
#    def __init__(self):
#        """shush pylint"""
#
#        i2c = busio.I2C(board.SCL, board.SDA)
#
#        # self.reset_pin = digitalio.DigitalInOut(board.IO13) # any pin!
#        self.oled = adafruit_ssd1306.SSD1306_I2C(
#            128, 32, i2c
#        )  # , reset=self.reset_pin)
#        self.oled.rotate(0)
#        self.line_1 = "line 1"
#        self.line_2 = "line 2"
#        self.line_3 = "line 3"
#        self.line_4 = "line 4"
#
#    def update_text(self, invert=0):
#        """shush pylint"""
#        white = 1
#        black = 0
#        if invert:
#            white = 0
#            black = 1
#        self.oled.fill(black)
#        self.oled.text(str(" " + self.line_1), 0, 0 * 1, white)
#        self.oled.text(str(" " + self.line_2), 0, 8 * 1, white)
#        self.oled.text(str(" " + self.line_3), 0, 8 * 2, white)
#        self.oled.text(str(" " + self.line_4), 0, 8 * 3, white)
#        self.oled.show()


class Button:
    """simple class for IO control"""

    def __init__(self):
        """shush pylint"""

        self.button = digitalio.DigitalInOut(board.D6)
        self.button.switch_to_input(pull=digitalio.Pull.UP)

    def is_pressed(self):
        """shush pylint"""
        if not self.button.value:
            return 1
        return 0


class Counter:
    """simple class for counting a thing"""

    def __init__(self):
        """shush pylint"""
        self.value = 0
        self.max = 20

    def increment(self):
        """shush pylint"""
        self.value += 1
        if self.value > self.max:
            self.value = 1


async def print_func():
    """shush pylint"""
    while 1:
        print(time.monotonic())
        print("print_func")
        await asyncio.sleep(0.1)


async def async_led_blink():
    """shush pylint"""
    while 1:
        led.toggle_led()
        await asyncio.sleep(0.2)


async def async_button_check():
    """shush pylint"""
    while 1:
        if butt.is_pressed():
            print("old:", counter_object.value)
            counter_object.increment()
            print("new:", counter_object.value)
        else:
            print("not pressed")
        await asyncio.sleep(0.1)


async def async_main():
    """shush pylint"""
    button_task = asyncio.create_task(async_button_check())
    led_task = asyncio.create_task(async_led_blink())
    #print_task = asyncio.create_task(print_func())
    await asyncio.gather(button_task, led_task)# print_task)



led = Led()
#display = Screen()
butt = Button()
print(butt.button.value)
counter_object = Counter()

#display.oled.fill(1)
#display.oled.show()

#display.oled.fill(0)
#display.oled.show()


print("begin")

print(time.monotonic())
asyncio.run(async_main())
print("end")

```

**Comment by xgpt** [comment] 2022-10-27 16:54
the first submitted code wasn't actually even possibly correct, due to some function naming errors related to sloppy debugging of mine. This code does run on 8x-beta 2

**Comment by dhalbert** [comment] 2022-10-27 16:59
Thanks for the testing! Can you come up with the simplest, smallest example? Remove all the commented out stuff, and all the pylint fixes No reason to run your code through pylint just for a test example.

@jepler Should I assign this to you? Regression from beta.2 to beta.3 in asyncio (so something in `_asyncio`?)

**Comment by xgpt** [comment] 2022-10-27 17:02
Happy to help, will need to be a little later in the day however.

**Comment by jepler** [comment] 2022-10-27 17:11
```py
import asyncio

async def main():  
    print("in async func")                                                      
                                                                                
                                                                                
print("before asyncio run")
asyncio.run(main())                                                             
print("after asyncio run")
```
It's pretty broken. A much smaller reproducer is above

**Closed** 2022-10-27 19:17 UTC
Labels: bug
