### ISSUE TITLE
Si1145

### ISSUE THREAD

**Issue by tonygo** [adafruit/circuitpython#1950] opened 2019-06-17 14:42 UTC
I've used this Adafruit Si1145 board with an Arduino and would really appreciate a CircuitPython driver to use with CircuitPlayground Express and Itsybitsy M4 Express. Now the sun might come out in UK anytime soon it would be really helpful.

**Comment by ladyada** [comment] 2019-06-17 16:00
duplicate of https://github.com/adafruit/circuitpython/issues/1941
please sub there :)

**Closed by ladyada** 2019-06-17 16:00 UTC
