### ISSUE TITLE
Cannot mount SD card but can write to it.

### ISSUE THREAD

**Issue by domdfcoding** [adafruit/circuitpython#8815] opened 2024-01-19 16:07 UTC
### CircuitPython version

```python
Adafruit CircuitPython 8.2.6 on 2023-09-12; Raspberry Pi Pico with rp2040

Adafruit CircuitPython 9.0.0-alpha.6-20-g4b92a4a9fa-dirty on 2024-01-18; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
import board
import digitalio
import storage
import adafruit_sdcard

import busio
#import bitbangio as busio

spi = busio.SPI(board.GP2, MOSI=board.GP3, MISO=board.GP4)
cs = digitalio.DigitalInOut(board.GP1)
sdcard = adafruit_sdcard.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)

print(vfs.getcwd())
with vfs.open("test.txt", "w") as fp:
	fp.write("this is a test")

print(list(vfs.ilistdir()))

storage.mount(vfs, "/sd")  # Line 20
```

### Behavior

```python
/
[('test.txt', 32768, 0, 14)]
Traceback (most recent call last):
  File "code.py", line 20, in <module>
OSError: [Errno 19] No such device
```

### Description

`storage.mount` reports "No such device" when an SD card is connected and can be read and written to using methods on the `storage.VfsFat` object. 

### Additional information

I tested this with both an [Adafruit Micro SD SPI or SDIO Card Breakout Board](https://www.adafruit.com/product/4682) and the Micro SD slot on a Waveshare RP2040-PiZero board, both with version 8.2.6 and the latest from GitHub. 

The SD card is a Transcend 4GB. I don't have any other small capacity cards on hand to test with.

The closest issue I can find is #8559 but that's for a different chip family.

**Comment by dhalbert** [comment] 2024-01-19 17:54
I tried reproducing this with a Pi Pico running 8.2.9, using the same breakout and pins as you. The card is an 8GB from Micro Center. I formatted it freshly to FAT32 with gparted on Linux.

By any chance is there already an `/sd` directory or file on CIRCUITPY before you try running the above?

I'd say try these things:
1. `storage.erase_filesystem()` on the Pico to make sure there's nothing corrupt about CIRCUITPY
2. Reformat the card externally (and say what you used if it still doesn't work).
3. Try another card. 32GB or maybe even 64GB should be fine.

By the way, you can use `sdcardio` instead of `adafruit_sd`. It is native. But I used `adafruit_sd` to test.

**Comment by evilhamsterman** [comment] 2024-02-25 22:12
@domdfcoding I ran into that problem using the adafruit_sdcard package, using the built in sdcardio package instead works fine and is easier since there's nothing extra to install. This was on 8.2.10 by the way

**Comment by dhalbert** [comment] 2024-03-08 22:14
Closing for now. Please reopen if you are still having trouble with the hints above.

**Closed by dhalbert** 2024-03-08 22:14 UTC
Labels: bug
